name: ECE285_PROJECT

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python==3.9.5
  - pip
  - ipykernel
  - jupyter==1.1.1
  - notebook==6.5.6
  - numpy
  - pandas
  - pillow
  - matplotlib
  - pytorch::pytorch
  - torchvision
  - pip:
    - einops
    - timm